repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 'v3.13.0'
    hooks:
      - id: commitizen
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.3
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format